const colors = {
  light: {
    text: "#0F172A",
    tint: "#0E7CF5",
    background: "#F0F7FF",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#0E7CF5",
    primaryForeground: "#FFFFFF",
    secondary: "#EFF6FF",
    secondaryForeground: "#1E40AF",
    muted: "#E2ECFA",
    mutedForeground: "#6B7F9E",
    accent: "#DBEAFE",
    accentForeground: "#1E40AF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#CBD5E1",
    input: "#E2E8F0",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    tankGreen: "#22C55E",
    tankOrange: "#F59E0B",
    tankRed: "#EF4444",
    motorOn: "#22C55E",
    motorOff: "#94A3B8",
    manualOverride: "#EF4444",
    supplyBlue: "#60A5FA",
  },
  dark: {
    text: "#E2EDF9",
    tint: "#60A5FA",
    background: "#060E18",
    foreground: "#E2EDF9",
    card: "#0F1E30",
    cardForeground: "#E2EDF9",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#162A42",
    secondaryForeground: "#93C5FD",
    muted: "#0F1E30",
    mutedForeground: "#6B8CAE",
    accent: "#1E3A5F",
    accentForeground: "#93C5FD",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3A5F",
    input: "#162A42",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    tankGreen: "#22C55E",
    tankOrange: "#F59E0B",
    tankRed: "#EF4444",
    motorOn: "#22C55E",
    motorOff: "#475569",
    manualOverride: "#EF4444",
    supplyBlue: "#60A5FA",
  },
  radius: 12,
};

export default colors;
